name: example
description: Gauge indicator example project.
publish_to: "none"
version: 1.0.0

scripts:
  release: flutter build web --release

environment:
  sdk: ^3.8.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  gauge_indicator:
    path: ../
  go_router: ^17.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/space.frag
