name: gauge_indicator
description: An animated, highly customizable, open source, Flutter gauge widget.
version: 0.4.4
homepage: https://github.com/gonuit/gauge_indicator

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

funding:
  - https://www.paypal.com/donate/?hosted_button_id=Z82R98MAR4URE
  - https://www.buymeacoffee.com/kamilklyta

topics:
  - widgets
  - animation
  - gauge
  - gauge-indicator
  - gauges

screenshots:
  - description: The gauge_indicator package thumbnail.
    path: thumbnail.png
